### ISSUE TITLE
Classycle fails on module-info.class entries

### ISSUE THREAD

**Issue by tobiasbaum** [maddingo/classycle#1]
This is probably the wrong place, but the Sourceforge page said I don't have permission to open issues there so I'll give this mirror a try:

I noticed that Classycle does not seem to handle the module-info files from new Java versions well. It fails with IndexOutOfBounds or NullPointerExceptions. I'll post some stacktraces below.

Is there any chance this will be fixed in an "official" version? Would it help to create a patch or PR? I guess that skipping these entries would be all that is needed.

**Comment by tobiasbaum** [comment]
Here are some stacktraces. I patched the most recent version from SVN with additional information about the location of the problem, but otherwise this is from a normal 1.4.2


============= Classycle V1.4.2 =============
========== by Franz-Josef Elmer ==========
read class files and create class graph ... Exception in thread "main" java.lang.RuntimeException: Problem with file jaxb-api-2.4.0-b180830.0359.jar
        at classycle.Parser.analyseClassFiles(Parser.java:263)
        at classycle.Parser.readClassFiles(Parser.java:153)
        at classycle.Analyser.createClassGraph(Analyser.java:112)
        at classycle.Analyser.readAndAnalyse(Analyser.java:402)
        at classycle.Analyser.main(Analyser.java:564)
Caused by: java.lang.RuntimeException: Problem with entry module-info.class
        at classycle.Parser.analyseClassFileFromZipEntry(Parser.java:281)
        at classycle.Parser.analyseClassFiles(Parser.java:259)
        ... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 7444
        at classycle.Parser.createNode(Parser.java:307)
        at classycle.Parser.analyseClassFileFromZipEntry(Parser.java:277)
        ... 5 more


============= Classycle V1.4.2 =============
========== by Franz-Josef Elmer ==========
read class files and create class graph ... Exception in thread "main" java.lang.RuntimeException: Problem with file slf4j-api-1.8.0-beta4.jar
        at classycle.Parser.analyseClassFiles(Parser.java:263)
        at classycle.Parser.readClassFiles(Parser.java:153)
        at classycle.Analyser.createClassGraph(Analyser.java:112)
        at classycle.Analyser.readAndAnalyse(Analyser.java:402)
        at classycle.Analyser.main(Analyser.java:564)
Caused by: java.lang.RuntimeException: Problem with entry META-INF/versions/9/module-info.class
        at classycle.Parser.analyseClassFileFromZipEntry(Parser.java:281)
        at classycle.Parser.analyseClassFiles(Parser.java:259)
        ... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5120
        at classycle.Parser.createNode(Parser.java:307)
        at classycle.Parser.analyseClassFileFromZipEntry(Parser.java:277)
        ... 5 more


============= Classycle V1.4.2 =============
========== by Franz-Josef Elmer ==========
read class files and create class graph ... Exception in thread "main" java.lang.RuntimeException: Problem with file internal.jar
        at classycle.Parser.analyseClassFiles(Parser.java:263)
        at classycle.Parser.readClassFiles(Parser.java:153)
        at classycle.Analyser.createClassGraph(Analyser.java:112)
        at classycle.Analyser.readAndAnalyse(Analyser.java:402)
        at classycle.Analyser.main(Analyser.java:564)
Caused by: java.lang.RuntimeException: Problem with entry module-info.class
        at classycle.Parser.analyseClassFileFromZipEntry(Parser.java:281)
        at classycle.Parser.analyseClassFiles(Parser.java:259)
        ... 4 more
Caused by: java.lang.NullPointerException
        at classycle.Parser.createNode(Parser.java:307)
        at classycle.Parser.analyseClassFileFromZipEntry(Parser.java:277)
        ... 5 more
